name: certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        conf:
          - MorphoV2

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install certora
        run: pip install certora-cli
      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.28/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc-0.8.28
      - name: Verify ${{ matrix.conf }}
        run: certoraRun certora/${{ matrix.conf }}.conf
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
