name: certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        conf:
          - CreatedObligations
          - ExactMath
          - Liquidate
          - Midnight
          - OnlyAuthorizedCanDecreaseShares
          - SharePrice
          - Solvency
          - WithdrawableMonotonicity

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install Jq
        uses: sergeysova/jq-action@v2

      - name: Run Certora Config Linter
        run: |
          file="certora/confs/${{ matrix.conf }}.conf"
          echo "Fix lint errors by applying the following diff to $file:"
          diff -u "$file" <(jq < "$file")

      - uses: actions/setup-python@v5

      - name: Install certora
        run: pip install certora-cli

      - name: Run Certora Specs Linter
        run: |
          file="certora/specs/${{ matrix.conf }}.spec"
          echo "Fix lint errors by applying the following diff to $file:"
          diff -u "$file" <(certoraCVLFormatter "$file")

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Copy solc
        run: |
          forge build
          cp ~/.svm/0.8.31/solc-0.8.31 /usr/local/bin

      - name: Verify ${{ matrix.conf }}
        run: certoraRun certora/confs/${{ matrix.conf }}.conf
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
