name: forge

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  foundry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Check formatting
        run: forge fmt --check
      - name: Run Forge tests
        run: forge test --deny warnings
